// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/edit_branch/presentation/bloc/edit_branch_full_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:either_dart/either.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i6;
import 'package:motogo_frontend/src/features/edit_branch/domain/usecases/update_branch_usecase.dart'
    as _i3;
import 'package:motogo_frontend/src/features/register_branch/domain/entities/branch_entity.dart'
    as _i7;
import 'package:motogo_frontend/src/features/register_branch/domain/repositories/branch_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBranchRepository_0 extends _i1.SmartFake
    implements _i2.BranchRepository {
  _FakeBranchRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UpdateBranchUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateBranchUseCase extends _i1.Mock
    implements _i3.UpdateBranchUseCase {
  MockUpdateBranchUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BranchRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBranchRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.BranchRepository);

  @override
  _i4.Future<_i5.Either<_i6.ErrorModel, (_i7.BranchEntity, String)>> call(
    String? id,
    _i7.BranchEntity? branch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id, branch]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.ErrorModel, (_i7.BranchEntity, String)>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.ErrorModel, (_i7.BranchEntity, String)>
                  >(this, Invocation.method(#call, [id, branch])),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.ErrorModel, (_i7.BranchEntity, String)>
          >);
}
