// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/motorcycle_profile_image/domain/usecases/delete_profile_image_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/motorcycle_profile_image/domain/entities/profile_image_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/motorcycle_profile_image/domain/repositories/profile_image_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileImageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileImageRepository extends _i1.Mock
    implements _i2.ProfileImageRepository {
  MockProfileImageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.ProfileImageEntity>>
  updateProfileImage(String? motorcycleId, String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileImage, [motorcycleId, imageUrl]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.ProfileImageEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.ProfileImageEntity>
                  >(
                    this,
                    Invocation.method(#updateProfileImage, [
                      motorcycleId,
                      imageUrl,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.ProfileImageEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.ProfileImageEntity>>
  getProfileImage(String? motorcycleId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileImage, [motorcycleId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.ProfileImageEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.ProfileImageEntity>
                  >(this, Invocation.method(#getProfileImage, [motorcycleId])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.ProfileImageEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deleteProfileImage(
    String? motorcycleId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfileImage, [motorcycleId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deleteProfileImage, [motorcycleId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
