// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/my_branches/presentation/bloc/my_branches_full_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/manage_franchise/domain/usecases/franchise_usecases.dart'
    as _i8;
import 'package:motogo_frontend/src/features/my_branches/domain/usecases/get_branches_usecase.dart'
    as _i2;
import 'package:motogo_frontend/src/features/register_branch/domain/entities/branch_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/register_franchise/domain/entities/franchise_entity.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetBranchesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBranchesUseCase extends _i1.Mock
    implements _i2.GetBranchesUseCase {
  MockGetBranchesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.BranchEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i6.BranchEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i6.BranchEntity>>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.BranchEntity>>>);
}

/// A class which mocks [ListFranchisesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockListFranchisesUseCase extends _i1.Mock
    implements _i8.ListFranchisesUseCase {
  MockListFranchisesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.FranchiseEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i9.FranchiseEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i9.FranchiseEntity>>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.FranchiseEntity>>>);
}
