// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/search_motorcycle_by_plate/domain/usecases/search_motorcycle_by_plate_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/search_motorcycle_by_plate/domain/entities/motorcycle_detail_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/search_motorcycle_by_plate/domain/repositories/search_motorcycle_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SearchMotorcycleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMotorcycleRepository extends _i1.Mock
    implements _i2.SearchMotorcycleRepository {
  MockSearchMotorcycleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.MotorcycleDetailEntity>>
  searchByPlate(String? plate) =>
      (super.noSuchMethod(
            Invocation.method(#searchByPlate, [plate]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.MotorcycleDetailEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.MotorcycleDetailEntity>
                  >(this, Invocation.method(#searchByPlate, [plate])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, _i6.MotorcycleDetailEntity>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> setSolution({
    required String? diagnosticId,
    required String? solution,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSolution, [], {
              #diagnosticId: diagnosticId,
              #solution: solution,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#setSolution, [], {
                  #diagnosticId: diagnosticId,
                  #solution: solution,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
