// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/my_motorcycles/presentation/bloc/my_motorcycles_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:either_dart/either.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i6;
import 'package:motogo_frontend/src/features/delete_motorcycle/domain/repositories/delete_motorcycle_repository.dart'
    as _i2;
import 'package:motogo_frontend/src/features/delete_motorcycle/domain/usecases/delete_motorcycle_usecase.dart'
    as _i9;
import 'package:motogo_frontend/src/features/my_motorcycles/domain/usecases/get_my_motorcycles_usecase.dart'
    as _i3;
import 'package:motogo_frontend/src/features/register_motorcycle/domain/entities/motorcycle_entity.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeleteMotorcycleRepository_0 extends _i1.SmartFake
    implements _i2.DeleteMotorcycleRepository {
  _FakeDeleteMotorcycleRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetMyMotorcyclesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMyMotorcyclesUseCase extends _i1.Mock
    implements _i3.GetMyMotorcyclesUseCase {
  MockGetMyMotorcyclesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.ErrorModel, List<_i7.MotorcycleEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.ErrorModel, List<_i7.MotorcycleEntity>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.ErrorModel, List<_i7.MotorcycleEntity>>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.ErrorModel, List<_i7.MotorcycleEntity>>
          >);
}

/// A class which mocks [DeleteMotorcycleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteMotorcycleUseCase extends _i1.Mock
    implements _i9.DeleteMotorcycleUseCase {
  MockDeleteMotorcycleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeleteMotorcycleRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeDeleteMotorcycleRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.DeleteMotorcycleRepository);

  @override
  _i4.Future<_i5.Either<_i6.ErrorModel, String>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<_i5.Either<_i6.ErrorModel, String>>.value(
              _i8.dummyValue<_i5.Either<_i6.ErrorModel, String>>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.ErrorModel, String>>);
}
