// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/branch_detail/domain/usecases/get_branch_detail_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/branch_detail/domain/entities/branch_detail_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/branch_detail/domain/repositories/branch_detail_repository.dart'
    as _i2;
import 'package:motogo_frontend/src/features/branch_schedules/domain/entities/schedule_detail_entity.dart'
    as _i9;
import 'package:motogo_frontend/src/features/branch_schedules/domain/entities/schedule_exception_entity.dart'
    as _i10;
import 'package:motogo_frontend/src/features/branch_services/domain/entities/branch_service_entity.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BranchDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBranchDetailRepository extends _i1.Mock
    implements _i2.BranchDetailRepository {
  MockBranchDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.BranchDetailEntity>> getDetail(
    String? branchId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDetail, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.BranchDetailEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.BranchDetailEntity>
                  >(this, Invocation.method(#getDetail, [branchId])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.BranchDetailEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.BranchServiceEntity>>>
  getServices(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#getServices, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i8.BranchServiceEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i8.BranchServiceEntity>>
                  >(this, Invocation.method(#getServices, [branchId])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i8.BranchServiceEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.ScheduleDetailEntity>>>
  getSchedules(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#getSchedules, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i9.ScheduleDetailEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i9.ScheduleDetailEntity>>
                  >(this, Invocation.method(#getSchedules, [branchId])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i9.ScheduleDetailEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i10.ScheduleExceptionEntity>>>
  getExceptions(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#getExceptions, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i10.ScheduleExceptionEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<
                      _i5.ErrorModel,
                      List<_i10.ScheduleExceptionEntity>
                    >
                  >(this, Invocation.method(#getExceptions, [branchId])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i10.ScheduleExceptionEntity>>
          >);
}
