// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/edit_profile/presentation/bloc/edit_profile_full_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/core/user/domain/entities/user_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/edit_profile/domain/usecases/get_person_usecase.dart'
    as _i2;
import 'package:motogo_frontend/src/features/edit_profile/domain/usecases/update_person_usecase.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetPersonUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPersonUsecase extends _i1.Mock implements _i2.GetPersonUsecase {
  MockGetPersonUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.UserEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.ErrorModel, _i6.UserEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.ErrorModel, _i6.UserEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.UserEntity>>);
}

/// A class which mocks [UpdatePersonUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePersonUsecase extends _i1.Mock
    implements _i8.UpdatePersonUsecase {
  MockUpdatePersonUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> call(_i6.UserEntity? user) =>
      (super.noSuchMethod(
            Invocation.method(#call, [user]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#call, [user]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
