// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/register_person/register_person_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/register_person/domain/entities/register_person_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/register_person/domain/entities/register_person_params.dart'
    as _i7;
import 'package:motogo_frontend/src/features/register_person/domain/repositories/register_person_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RegisterPersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterPersonRepository extends _i1.Mock
    implements _i2.RegisterPersonRepository {
  MockRegisterPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.PersonEntity>> savePerson(
    _i7.RegisterPersonParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#savePerson, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i5.ErrorModel, _i6.PersonEntity>>.value(
                  _i8.dummyValue<_i4.Either<_i5.ErrorModel, _i6.PersonEntity>>(
                    this,
                    Invocation.method(#savePerson, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.PersonEntity>>);
}
