// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/core/catalogs/catalogs_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/catalogs/data/datasources/catalogs_data_source.dart'
    as _i2;
import 'package:motogo_frontend/src/core/catalogs/data/models/branch_type_model.dart'
    as _i10;
import 'package:motogo_frontend/src/core/catalogs/data/models/brand_model.dart'
    as _i6;
import 'package:motogo_frontend/src/core/catalogs/data/models/city_model.dart'
    as _i9;
import 'package:motogo_frontend/src/core/catalogs/data/models/department_model.dart'
    as _i8;
import 'package:motogo_frontend/src/core/catalogs/data/models/displacement_range_model.dart'
    as _i12;
import 'package:motogo_frontend/src/core/catalogs/data/models/service_model.dart'
    as _i11;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CatalogsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogsDataSource extends _i1.Mock
    implements _i2.CatalogsDataSource {
  MockCatalogsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.BrandModel>>> getBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getBrands, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i6.BrandModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i6.BrandModel>>
                  >(this, Invocation.method(#getBrands, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.BrandModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.DepartmentModel>>>
  getDepartments() =>
      (super.noSuchMethod(
            Invocation.method(#getDepartments, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i8.DepartmentModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i8.DepartmentModel>>
                  >(this, Invocation.method(#getDepartments, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.DepartmentModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.CityModel>>>
  getCitiesByDepartment(String? departmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getCitiesByDepartment, [departmentId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i9.CityModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i9.CityModel>>
                  >(
                    this,
                    Invocation.method(#getCitiesByDepartment, [departmentId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.CityModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i10.BranchTypeModel>>>
  getBranchTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getBranchTypes, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i10.BranchTypeModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i10.BranchTypeModel>>
                  >(this, Invocation.method(#getBranchTypes, [])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i10.BranchTypeModel>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i11.ServiceModel>>> getServices({
    String? serviceType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getServices, [], {#serviceType: serviceType}),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i11.ServiceModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i11.ServiceModel>>
                  >(
                    this,
                    Invocation.method(#getServices, [], {
                      #serviceType: serviceType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i11.ServiceModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<String>>> getServiceTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getServiceTypes, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.ErrorModel, List<String>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.ErrorModel, List<String>>>(
                    this,
                    Invocation.method(#getServiceTypes, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<String>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i12.DisplacementRangeModel>>>
  getDisplacementRanges() =>
      (super.noSuchMethod(
            Invocation.method(#getDisplacementRanges, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i12.DisplacementRangeModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<
                      _i5.ErrorModel,
                      List<_i12.DisplacementRangeModel>
                    >
                  >(this, Invocation.method(#getDisplacementRanges, [])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i12.DisplacementRangeModel>>
          >);
}
