// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/technical_catalogs/data/repositories/category_lines_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/technical_catalogs/data/datasources/category_lines_datasource.dart'
    as _i2;
import 'package:motogo_frontend/src/features/technical_catalogs/data/models/category_line_model.dart'
    as _i8;
import 'package:motogo_frontend/src/features/technical_catalogs/data/models/category_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoryLinesDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryLinesDataSource extends _i1.Mock
    implements _i2.CategoryLinesDataSource {
  MockCategoryLinesDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.CategoryModel>>>
  getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i6.CategoryModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i6.CategoryModel>>
                  >(this, Invocation.method(#getCategories, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.CategoryModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.CategoryLineModel>>>
  getCategoryLines(String? categoryName) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryLines, [categoryName]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i8.CategoryLineModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i8.CategoryLineModel>>
                  >(this, Invocation.method(#getCategoryLines, [categoryName])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i8.CategoryLineModel>>
          >);
}
