// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/motorcycle_evidence/motorcycle_evidence_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i9;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/core/services/firebase/storage_service.dart'
    as _i8;
import 'package:motogo_frontend/src/features/motorcycle_evidence/domain/entities/motorcycle_evidence_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/motorcycle_evidence/domain/repositories/motorcycle_evidence_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MotorcycleEvidenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMotorcycleEvidenceRepository extends _i1.Mock
    implements _i2.MotorcycleEvidenceRepository {
  MockMotorcycleEvidenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.MotorcycleEvidenceEntity>>>
  getEvidence({required String? motorcycleId}) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidence, [], {#motorcycleId: motorcycleId}),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i6.MotorcycleEvidenceEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<
                      _i5.ErrorModel,
                      List<_i6.MotorcycleEvidenceEntity>
                    >
                  >(
                    this,
                    Invocation.method(#getEvidence, [], {
                      #motorcycleId: motorcycleId,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i6.MotorcycleEvidenceEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.MotorcycleEvidenceEntity>>
  createEvidence({
    required String? motorcycleId,
    required String? imageUrl,
    String? angle,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEvidence, [], {
              #motorcycleId: motorcycleId,
              #imageUrl: imageUrl,
              #angle: angle,
              #description: description,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.MotorcycleEvidenceEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.MotorcycleEvidenceEntity>
                  >(
                    this,
                    Invocation.method(#createEvidence, [], {
                      #motorcycleId: motorcycleId,
                      #imageUrl: imageUrl,
                      #angle: angle,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, _i6.MotorcycleEvidenceEntity>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deleteEvidence({
    required String? motorcycleId,
    required String? evidenceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvidence, [], {
              #motorcycleId: motorcycleId,
              #evidenceId: evidenceId,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deleteEvidence, [], {
                  #motorcycleId: motorcycleId,
                  #evidenceId: evidenceId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i8.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, void>> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, void>>(
                this,
                Invocation.method(#authenticate, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, void>>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> uploadImage({
    required String? storagePath,
    required _i9.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [], {
              #storagePath: storagePath,
              #file: file,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#uploadImage, [], {
                  #storagePath: storagePath,
                  #file: file,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> uploadBranchImage({
    required String? branchId,
    required _i9.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBranchImage, [], {
              #branchId: branchId,
              #file: file,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#uploadBranchImage, [], {
                  #branchId: branchId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> uploadUserAvatar({
    required String? userId,
    required _i9.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadUserAvatar, [], {
              #userId: userId,
              #file: file,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#uploadUserAvatar, [], {
                  #userId: userId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> uploadMotorcycleImage({
    required String? motorcycleId,
    required _i9.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMotorcycleImage, [], {
              #motorcycleId: motorcycleId,
              #file: file,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#uploadMotorcycleImage, [], {
                  #motorcycleId: motorcycleId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<String>>> uploadMultiple({
    required String? basePath,
    required List<_i9.File>? files,
    int? maxImages = 4,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMultiple, [], {
              #basePath: basePath,
              #files: files,
              #maxImages: maxImages,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.ErrorModel, List<String>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.ErrorModel, List<String>>>(
                    this,
                    Invocation.method(#uploadMultiple, [], {
                      #basePath: basePath,
                      #files: files,
                      #maxImages: maxImages,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<String>>>);
}
