// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/branch_schedules/presentation/bloc/branch_schedule_full_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/branch_schedules/domain/entities/day_entity.dart'
    as _i8;
import 'package:motogo_frontend/src/features/branch_schedules/domain/entities/schedule_detail_entity.dart'
    as _i9;
import 'package:motogo_frontend/src/features/branch_schedules/domain/entities/schedule_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/branch_schedules/domain/entities/schedule_exception_entity.dart'
    as _i10;
import 'package:motogo_frontend/src/features/branch_schedules/domain/repositories/branch_schedule_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BranchScheduleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBranchScheduleRepository extends _i1.Mock
    implements _i2.BranchScheduleRepository {
  MockBranchScheduleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.ScheduleEntity?>> getSchedule(
    String? branchId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSchedule, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.ScheduleEntity?>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.ScheduleEntity?>
                  >(this, Invocation.method(#getSchedule, [branchId])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.ScheduleEntity?>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>>
  createSchedule(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#createSchedule, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
                  >(this, Invocation.method(#createSchedule, [branchId])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>>
  updateSchedule(
    String? branchId, {
    bool? active,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSchedule,
              [branchId],
              {#active: active, #startDate: startDate, #endDate: endDate},
            ),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
                  >(
                    this,
                    Invocation.method(
                      #updateSchedule,
                      [branchId],
                      {
                        #active: active,
                        #startDate: startDate,
                        #endDate: endDate,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deleteSchedule(
    String? branchId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSchedule, [branchId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deleteSchedule, [branchId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>>
  activateSchedule(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#activateSchedule, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
                  >(this, Invocation.method(#activateSchedule, [branchId])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>>
  deactivateSchedule(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateSchedule, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
                  >(this, Invocation.method(#deactivateSchedule, [branchId])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, (_i6.ScheduleEntity, String)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.DayEntity>>>
  getDaysCatalog() =>
      (super.noSuchMethod(
            Invocation.method(#getDaysCatalog, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i8.DayEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i8.DayEntity>>
                  >(this, Invocation.method(#getDaysCatalog, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.DayEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.ScheduleDetailEntity>>>
  getScheduleDetails(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#getScheduleDetails, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i9.ScheduleDetailEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i9.ScheduleDetailEntity>>
                  >(this, Invocation.method(#getScheduleDetails, [branchId])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i9.ScheduleDetailEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, (_i9.ScheduleDetailEntity, String)>>
  createScheduleDetail(
    String? branchId, {
    required int? dayOfWeek,
    required String? openingTime,
    required String? closingTime,
    required bool? isClosed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createScheduleDetail,
              [branchId],
              {
                #dayOfWeek: dayOfWeek,
                #openingTime: openingTime,
                #closingTime: closingTime,
                #isClosed: isClosed,
              },
            ),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, (_i9.ScheduleDetailEntity, String)>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<
                      _i5.ErrorModel,
                      (_i9.ScheduleDetailEntity, String)
                    >
                  >(
                    this,
                    Invocation.method(
                      #createScheduleDetail,
                      [branchId],
                      {
                        #dayOfWeek: dayOfWeek,
                        #openingTime: openingTime,
                        #closingTime: closingTime,
                        #isClosed: isClosed,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, (_i9.ScheduleDetailEntity, String)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> updateScheduleDetail(
    String? detailId, {
    required String? openingTime,
    required String? closingTime,
    required bool? isClosed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateScheduleDetail,
              [detailId],
              {
                #openingTime: openingTime,
                #closingTime: closingTime,
                #isClosed: isClosed,
              },
            ),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(
                  #updateScheduleDetail,
                  [detailId],
                  {
                    #openingTime: openingTime,
                    #closingTime: closingTime,
                    #isClosed: isClosed,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deleteScheduleDetail(
    String? detailId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteScheduleDetail, [detailId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deleteScheduleDetail, [detailId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i10.ScheduleExceptionEntity>>>
  getScheduleExceptions(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#getScheduleExceptions, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i10.ScheduleExceptionEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<
                      _i5.ErrorModel,
                      List<_i10.ScheduleExceptionEntity>
                    >
                  >(
                    this,
                    Invocation.method(#getScheduleExceptions, [branchId]),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i10.ScheduleExceptionEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, (_i10.ScheduleExceptionEntity, String)>>
  createScheduleException(
    String? branchId, {
    required String? exceptionStartDate,
    String? exceptionEndDate,
    required String? openingTime,
    required String? closingTime,
    required bool? isClosed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createScheduleException,
              [branchId],
              {
                #exceptionStartDate: exceptionStartDate,
                #exceptionEndDate: exceptionEndDate,
                #openingTime: openingTime,
                #closingTime: closingTime,
                #isClosed: isClosed,
              },
            ),
            returnValue:
                _i3.Future<
                  _i4.Either<
                    _i5.ErrorModel,
                    (_i10.ScheduleExceptionEntity, String)
                  >
                >.value(
                  _i7.dummyValue<
                    _i4.Either<
                      _i5.ErrorModel,
                      (_i10.ScheduleExceptionEntity, String)
                    >
                  >(
                    this,
                    Invocation.method(
                      #createScheduleException,
                      [branchId],
                      {
                        #exceptionStartDate: exceptionStartDate,
                        #exceptionEndDate: exceptionEndDate,
                        #openingTime: openingTime,
                        #closingTime: closingTime,
                        #isClosed: isClosed,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, (_i10.ScheduleExceptionEntity, String)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> updateScheduleException(
    String? exceptionId, {
    required String? openingTime,
    required String? closingTime,
    required bool? isClosed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateScheduleException,
              [exceptionId],
              {
                #openingTime: openingTime,
                #closingTime: closingTime,
                #isClosed: isClosed,
              },
            ),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(
                  #updateScheduleException,
                  [exceptionId],
                  {
                    #openingTime: openingTime,
                    #closingTime: closingTime,
                    #isClosed: isClosed,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deleteScheduleException(
    String? exceptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteScheduleException, [exceptionId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deleteScheduleException, [exceptionId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> activateScheduleException(
    String? exceptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#activateScheduleException, [exceptionId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#activateScheduleException, [exceptionId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deactivateScheduleException(
    String? exceptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateScheduleException, [exceptionId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deactivateScheduleException, [exceptionId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
