// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/admin_services/admin_service_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/admin_services/domain/entities/admin_service_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/admin_services/domain/repositories/admin_service_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AdminServiceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminServiceRepository extends _i1.Mock
    implements _i2.AdminServiceRepository {
  MockAdminServiceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.AdminServiceEntity>>>
  getServices() =>
      (super.noSuchMethod(
            Invocation.method(#getServices, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i6.AdminServiceEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i6.AdminServiceEntity>>
                  >(this, Invocation.method(#getServices, [])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i6.AdminServiceEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.AdminServiceEntity>> updateService({
    required String? serviceId,
    required String? name,
    required String? serviceType,
    String? description,
    bool? isActive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateService, [], {
              #serviceId: serviceId,
              #name: name,
              #serviceType: serviceType,
              #description: description,
              #isActive: isActive,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.AdminServiceEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.AdminServiceEntity>
                  >(
                    this,
                    Invocation.method(#updateService, [], {
                      #serviceId: serviceId,
                      #name: name,
                      #serviceType: serviceType,
                      #description: description,
                      #isActive: isActive,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.AdminServiceEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> activateService(
    String? serviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#activateService, [serviceId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#activateService, [serviceId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deactivateService(
    String? serviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateService, [serviceId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deactivateService, [serviceId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
