// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/completed_services/domain/usecases/get_service_transitions_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/completed_services/data/model/completed_service_model.dart'
    as _i8;
import 'package:motogo_frontend/src/features/completed_services/data/model/register_completed_service_model.dart'
    as _i6;
import 'package:motogo_frontend/src/features/completed_services/data/model/status_transition_model.dart'
    as _i9;
import 'package:motogo_frontend/src/features/completed_services/domain/repositories/completed_services_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CompletedServicesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompletedServicesRepository extends _i1.Mock
    implements _i2.CompletedServicesRepository {
  MockCompletedServicesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> registerCompletedService(
    _i6.RegisterCompletedServiceModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerCompletedService, [request]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#registerCompletedService, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.CompletedServiceModel>>>
  getCompletedServicesByBranch(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedServicesByBranch, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i8.CompletedServiceModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i8.CompletedServiceModel>>
                  >(
                    this,
                    Invocation.method(#getCompletedServicesByBranch, [
                      branchId,
                    ]),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i8.CompletedServiceModel>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.CompletedServiceModel>>>
  getCompletedServicesByMotorcycle(String? motorcycleId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedServicesByMotorcycle, [
              motorcycleId,
            ]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i8.CompletedServiceModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i8.CompletedServiceModel>>
                  >(
                    this,
                    Invocation.method(#getCompletedServicesByMotorcycle, [
                      motorcycleId,
                    ]),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i8.CompletedServiceModel>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> updateServiceStatus(
    String? serviceId,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateServiceStatus, [serviceId, newStatus]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#updateServiceStatus, [serviceId, newStatus]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.StatusTransitionModel>>>
  getServiceTransitions(String? serviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getServiceTransitions, [serviceId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i9.StatusTransitionModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i9.StatusTransitionModel>>
                  >(
                    this,
                    Invocation.method(#getServiceTransitions, [serviceId]),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i9.StatusTransitionModel>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deleteCompletedService(
    String? serviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCompletedService, [serviceId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deleteCompletedService, [serviceId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
