// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/diagnostic/domain/usecase/create_diagnostic_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/diagnostic/domain/entity/diagnostic_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/diagnostic/domain/repository/diagnostic_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DiagnosticRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiagnosticRepository extends _i1.Mock
    implements _i2.DiagnosticRepository {
  MockDiagnosticRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.DiagnosticEntity>>
  createDiagnostic({
    required String? motorcycleId,
    required String? problemDescription,
    String? branchId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDiagnostic, [], {
              #motorcycleId: motorcycleId,
              #problemDescription: problemDescription,
              #branchId: branchId,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.DiagnosticEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.DiagnosticEntity>
                  >(
                    this,
                    Invocation.method(#createDiagnostic, [], {
                      #motorcycleId: motorcycleId,
                      #problemDescription: problemDescription,
                      #branchId: branchId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.DiagnosticEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.DiagnosticEntity>>>
  listDiagnostics({required String? motorcycleId}) =>
      (super.noSuchMethod(
            Invocation.method(#listDiagnostics, [], {
              #motorcycleId: motorcycleId,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i6.DiagnosticEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i6.DiagnosticEntity>>
                  >(
                    this,
                    Invocation.method(#listDiagnostics, [], {
                      #motorcycleId: motorcycleId,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i6.DiagnosticEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.DiagnosticEntity>> getDiagnostic({
    required String? motorcycleId,
    required String? diagnosticId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiagnostic, [], {
              #motorcycleId: motorcycleId,
              #diagnosticId: diagnosticId,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.DiagnosticEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.DiagnosticEntity>
                  >(
                    this,
                    Invocation.method(#getDiagnostic, [], {
                      #motorcycleId: motorcycleId,
                      #diagnosticId: diagnosticId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.DiagnosticEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> updateDiagnostic({
    required String? motorcycleId,
    required String? diagnosticId,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiagnostic, [], {
              #motorcycleId: motorcycleId,
              #diagnosticId: diagnosticId,
              #data: data,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#updateDiagnostic, [], {
                  #motorcycleId: motorcycleId,
                  #diagnosticId: diagnosticId,
                  #data: data,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deleteDiagnostic({
    required String? motorcycleId,
    required String? diagnosticId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDiagnostic, [], {
              #motorcycleId: motorcycleId,
              #diagnosticId: diagnosticId,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deleteDiagnostic, [], {
                  #motorcycleId: motorcycleId,
                  #diagnosticId: diagnosticId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
