// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/manage_franchise/presentation/bloc/manage_franchise_full_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/manage_franchise/domain/usecases/franchise_usecases.dart'
    as _i2;
import 'package:motogo_frontend/src/features/my_branches/domain/usecases/get_branches_usecase.dart'
    as _i8;
import 'package:motogo_frontend/src/features/register_branch/domain/entities/branch_entity.dart'
    as _i9;
import 'package:motogo_frontend/src/features/register_franchise/domain/entities/franchise_entity.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetFranchiseUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFranchiseUseCase extends _i1.Mock
    implements _i2.GetFranchiseUseCase {
  MockGetFranchiseUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.FranchiseEntity>> call(
    String? franchiseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [franchiseId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.FranchiseEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.FranchiseEntity>
                  >(this, Invocation.method(#call, [franchiseId])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.FranchiseEntity>>);
}

/// A class which mocks [UpdateFranchiseUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateFranchiseUseCase extends _i1.Mock
    implements _i2.UpdateFranchiseUseCase {
  MockUpdateFranchiseUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.FranchiseEntity>> call(
    String? franchiseId,
    _i6.FranchiseEntity? franchise,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [franchiseId, franchise]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.FranchiseEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.FranchiseEntity>
                  >(this, Invocation.method(#call, [franchiseId, franchise])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.FranchiseEntity>>);
}

/// A class which mocks [DeleteFranchiseUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteFranchiseUseCase extends _i1.Mock
    implements _i2.DeleteFranchiseUseCase {
  MockDeleteFranchiseUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> call(String? franchiseId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [franchiseId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#call, [franchiseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}

/// A class which mocks [LinkBranchToFranchiseUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinkBranchToFranchiseUseCase extends _i1.Mock
    implements _i2.LinkBranchToFranchiseUseCase {
  MockLinkBranchToFranchiseUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> call(
    String? branchId,
    String? franchiseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [branchId, franchiseId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#call, [branchId, franchiseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}

/// A class which mocks [UnlinkBranchFromFranchiseUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnlinkBranchFromFranchiseUseCase extends _i1.Mock
    implements _i2.UnlinkBranchFromFranchiseUseCase {
  MockUnlinkBranchFromFranchiseUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> call(
    String? branchId,
    String? franchiseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [branchId, franchiseId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#call, [branchId, franchiseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}

/// A class which mocks [GetBranchesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBranchesUseCase extends _i1.Mock
    implements _i8.GetBranchesUseCase {
  MockGetBranchesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.BranchEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i9.BranchEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i9.BranchEntity>>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.BranchEntity>>>);
}
