// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/branch_services/presentation/bloc/branch_services_full_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/catalogs/domain/entities/branch_type_entity.dart'
    as _i10;
import 'package:motogo_frontend/src/core/catalogs/domain/entities/brand_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/core/catalogs/domain/entities/city_entity.dart'
    as _i9;
import 'package:motogo_frontend/src/core/catalogs/domain/entities/department_entity.dart'
    as _i8;
import 'package:motogo_frontend/src/core/catalogs/domain/entities/displacement_range_entity.dart'
    as _i12;
import 'package:motogo_frontend/src/core/catalogs/domain/entities/service_entity.dart'
    as _i11;
import 'package:motogo_frontend/src/core/catalogs/domain/repositories/catalogs_repository.dart'
    as _i2;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/branch_services/data/datasources/branch_services_datasource.dart'
    as _i13;
import 'package:motogo_frontend/src/features/branch_services/data/models/branch_service_model.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CatalogsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogsRepository extends _i1.Mock
    implements _i2.CatalogsRepository {
  MockCatalogsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.BrandEntity>>> getBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getBrands, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i6.BrandEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i6.BrandEntity>>
                  >(this, Invocation.method(#getBrands, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.BrandEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.DepartmentEntity>>>
  getDepartments() =>
      (super.noSuchMethod(
            Invocation.method(#getDepartments, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i8.DepartmentEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i8.DepartmentEntity>>
                  >(this, Invocation.method(#getDepartments, [])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i8.DepartmentEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.CityEntity>>>
  getCitiesByDepartment(String? departmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getCitiesByDepartment, [departmentId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i9.CityEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i9.CityEntity>>
                  >(
                    this,
                    Invocation.method(#getCitiesByDepartment, [departmentId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i9.CityEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i10.BranchTypeEntity>>>
  getBranchTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getBranchTypes, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i10.BranchTypeEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i10.BranchTypeEntity>>
                  >(this, Invocation.method(#getBranchTypes, [])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i10.BranchTypeEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i11.ServiceEntity>>> getServices({
    String? serviceType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getServices, [], {#serviceType: serviceType}),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i11.ServiceEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i11.ServiceEntity>>
                  >(
                    this,
                    Invocation.method(#getServices, [], {
                      #serviceType: serviceType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<_i11.ServiceEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<String>>> getServiceTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getServiceTypes, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.ErrorModel, List<String>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.ErrorModel, List<String>>>(
                    this,
                    Invocation.method(#getServiceTypes, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, List<String>>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i12.DisplacementRangeEntity>>>
  getDisplacementRanges() =>
      (super.noSuchMethod(
            Invocation.method(#getDisplacementRanges, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i12.DisplacementRangeEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<
                      _i5.ErrorModel,
                      List<_i12.DisplacementRangeEntity>
                    >
                  >(this, Invocation.method(#getDisplacementRanges, [])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i12.DisplacementRangeEntity>>
          >);
}

/// A class which mocks [BranchServicesDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBranchServicesDataSource extends _i1.Mock
    implements _i13.BranchServicesDataSource {
  MockBranchServicesDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i14.BranchServiceModel>>>
  getBranchServices(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#getBranchServices, [branchId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i14.BranchServiceModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i14.BranchServiceModel>>
                  >(this, Invocation.method(#getBranchServices, [branchId])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i14.BranchServiceModel>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> associateService(
    String? branchId,
    String? serviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#associateService, [branchId, serviceId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#associateService, [branchId, serviceId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> dissociateService(
    String? branchId,
    String? serviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#dissociateService, [branchId, serviceId]),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#dissociateService, [branchId, serviceId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
