// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/diagnostic_permission/domain/usecase/diagnostic_permission_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/diagnostic_permission/domain/entity/diagnostic_permission_entity.dart'
    as _i8;
import 'package:motogo_frontend/src/features/diagnostic_permission/domain/entity/permission_grant_result.dart'
    as _i6;
import 'package:motogo_frontend/src/features/diagnostic_permission/domain/repository/diagnostic_permission_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DiagnosticPermissionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiagnosticPermissionRepository extends _i1.Mock
    implements _i2.DiagnosticPermissionRepository {
  MockDiagnosticPermissionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i6.PermissionGrantResult>>
  grantPermission({
    required String? motorcycleId,
    required String? branchId,
    required bool? active,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#grantPermission, [], {
              #motorcycleId: motorcycleId,
              #branchId: branchId,
              #active: active,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i6.PermissionGrantResult>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i6.PermissionGrantResult>
                  >(
                    this,
                    Invocation.method(#grantPermission, [], {
                      #motorcycleId: motorcycleId,
                      #branchId: branchId,
                      #active: active,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i6.PermissionGrantResult>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i8.DiagnosticPermissionEntity>>>
  listPermissions({required String? motorcycleId}) =>
      (super.noSuchMethod(
            Invocation.method(#listPermissions, [], {
              #motorcycleId: motorcycleId,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<
                    _i5.ErrorModel,
                    List<_i8.DiagnosticPermissionEntity>
                  >
                >.value(
                  _i7.dummyValue<
                    _i4.Either<
                      _i5.ErrorModel,
                      List<_i8.DiagnosticPermissionEntity>
                    >
                  >(
                    this,
                    Invocation.method(#listPermissions, [], {
                      #motorcycleId: motorcycleId,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i8.DiagnosticPermissionEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> revokePermission({
    required String? motorcycleId,
    required String? branchId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#revokePermission, [], {
              #motorcycleId: motorcycleId,
              #branchId: branchId,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#revokePermission, [], {
                  #motorcycleId: motorcycleId,
                  #branchId: branchId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
