// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/user_home/presentation/bloc/user_home_full_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:geolocator/geolocator.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/core/services/location_service.dart' as _i8;
import 'package:motogo_frontend/src/features/user_home/domain/entities/branch_marker_entity.dart'
    as _i6;
import 'package:motogo_frontend/src/features/user_home/domain/usecases/get_nearby_branches_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetNearbyBranchesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNearbyBranchesUseCase extends _i1.Mock
    implements _i2.GetNearbyBranchesUseCase {
  MockGetNearbyBranchesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.BranchMarkerEntity>>> call({
    required double? latitude,
    required double? longitude,
    double? radiusKm = 10.0,
    String? type,
    String? brand,
    String? displacementRange,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
              #type: type,
              #brand: brand,
              #displacementRange: displacementRange,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i6.BranchMarkerEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, List<_i6.BranchMarkerEntity>>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #radiusKm: radiusKm,
                      #type: type,
                      #brand: brand,
                      #displacementRange: displacementRange,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i6.BranchMarkerEntity>>
          >);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i8.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isLocationAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationAvailable, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i9.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i3.Future<_i9.LocationPermission>.value(
              _i9.LocationPermission.denied,
            ),
          )
          as _i3.Future<_i9.LocationPermission>);

  @override
  _i3.Future<_i9.Position?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i3.Future<_i9.Position?>.value(),
          )
          as _i3.Future<_i9.Position?>);

  @override
  _i3.Stream<_i9.Position> getPositionStream({int? distanceFilter = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, [], {
              #distanceFilter: distanceFilter,
            }),
            returnValue: _i3.Stream<_i9.Position>.empty(),
          )
          as _i3.Stream<_i9.Position>);

  @override
  void startListening({
    required void Function(_i9.Position)? onPosition,
    int? distanceFilter = 10,
  }) => super.noSuchMethod(
    Invocation.method(#startListening, [], {
      #onPosition: onPosition,
      #distanceFilter: distanceFilter,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void stopListening() => super.noSuchMethod(
    Invocation.method(#stopListening, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
