// Mocks generated by Mockito 5.4.4 from annotations
// in motogo_frontend/test/features/motorcycle_evidence/data/repositories/motorcycle_evidence_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:motogo_frontend/src/core/errors/error_model.dart' as _i5;
import 'package:motogo_frontend/src/features/motorcycle_evidence/data/datasources/motorcycle_evidence_datasource.dart'
    as _i2;
import 'package:motogo_frontend/src/features/motorcycle_evidence/data/models/motorcycle_evidence_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MotorcycleEvidenceDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMotorcycleEvidenceDataSource extends _i1.Mock
    implements _i2.MotorcycleEvidenceDataSource {
  MockMotorcycleEvidenceDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, List<_i6.MotorcycleEvidenceModel>>>
  getEvidence({required String? motorcycleId}) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidence, [], {#motorcycleId: motorcycleId}),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, List<_i6.MotorcycleEvidenceModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<
                      _i5.ErrorModel,
                      List<_i6.MotorcycleEvidenceModel>
                    >
                  >(
                    this,
                    Invocation.method(#getEvidence, [], {
                      #motorcycleId: motorcycleId,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.ErrorModel, List<_i6.MotorcycleEvidenceModel>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, _i2.EvidenceResponse>> createEvidence({
    required String? motorcycleId,
    required String? imageUrl,
    String? angle,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEvidence, [], {
              #motorcycleId: motorcycleId,
              #imageUrl: imageUrl,
              #angle: angle,
              #description: description,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.ErrorModel, _i2.EvidenceResponse>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.ErrorModel, _i2.EvidenceResponse>
                  >(
                    this,
                    Invocation.method(#createEvidence, [], {
                      #motorcycleId: motorcycleId,
                      #imageUrl: imageUrl,
                      #angle: angle,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, _i2.EvidenceResponse>>);

  @override
  _i3.Future<_i4.Either<_i5.ErrorModel, String>> deleteEvidence({
    required String? motorcycleId,
    required String? evidenceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvidence, [], {
              #motorcycleId: motorcycleId,
              #evidenceId: evidenceId,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.ErrorModel, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.ErrorModel, String>>(
                this,
                Invocation.method(#deleteEvidence, [], {
                  #motorcycleId: motorcycleId,
                  #evidenceId: evidenceId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.ErrorModel, String>>);
}
